// Code generated by ent, DO NOT EDIT.

package privateshare

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hellohq/hqservice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldUserID, v))
}

// AssetInfoID applies equality check predicate on the "asset_info_id" field. It's identical to AssetInfoIDEQ.
func AssetInfoID(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldAssetInfoID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNotNull(FieldUserID))
}

// AssetInfoIDEQ applies the EQ predicate on the "asset_info_id" field.
func AssetInfoIDEQ(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldAssetInfoID, v))
}

// AssetInfoIDNEQ applies the NEQ predicate on the "asset_info_id" field.
func AssetInfoIDNEQ(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNEQ(FieldAssetInfoID, v))
}

// AssetInfoIDIn applies the In predicate on the "asset_info_id" field.
func AssetInfoIDIn(vs ...uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldIn(FieldAssetInfoID, vs...))
}

// AssetInfoIDNotIn applies the NotIn predicate on the "asset_info_id" field.
func AssetInfoIDNotIn(vs ...uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNotIn(FieldAssetInfoID, vs...))
}

// AssetInfoIDGT applies the GT predicate on the "asset_info_id" field.
func AssetInfoIDGT(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGT(FieldAssetInfoID, v))
}

// AssetInfoIDGTE applies the GTE predicate on the "asset_info_id" field.
func AssetInfoIDGTE(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGTE(FieldAssetInfoID, v))
}

// AssetInfoIDLT applies the LT predicate on the "asset_info_id" field.
func AssetInfoIDLT(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLT(FieldAssetInfoID, v))
}

// AssetInfoIDLTE applies the LTE predicate on the "asset_info_id" field.
func AssetInfoIDLTE(v uint) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLTE(FieldAssetInfoID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PrivateShare {
	return predicate.PrivateShare(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PrivateShare {
	return predicate.PrivateShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PrivateShare {
	return predicate.PrivateShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrivateShare) predicate.PrivateShare {
	return predicate.PrivateShare(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrivateShare) predicate.PrivateShare {
	return predicate.PrivateShare(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrivateShare) predicate.PrivateShare {
	return predicate.PrivateShare(func(s *sql.Selector) {
		p(s.Not())
	})
}
