#!/bin/sh

scriptsdir=$( dirname -- "$0"; )
cd $scriptsdir/../../

if ! command -v doppler &> /dev/null; then
    echo "Doppler is not installed or not in PATH, please run 'task scripts:install:doppler' and try again"

elif ! command -v air &> /dev/null; then
    echo "Air is not installed or not in GOPATH, please run 'task scripts:install:gotools' and try again. Make sure your shell can lookup for GOBIN path by 'export PATH=$PATH:$(go env GOPATH)/bin'"
else
    echo "HQ service started by exec built app"
    doppler run -- docker compose down --volumes &&
    doppler run -- docker compose up -d --remove-orphans &&
    doppler run -- air serve
fi
