#!/bin/bash
set -e -o pipefail
export PATH="$PWD/.gobincache:$PATH"
go generate
set -x

scriptsdir=$( dirname -- "$0"; )
cd $scriptsdir/../../

hadolint docker/Dockerfile

go test -race -covermode atomic -coverprofile=coverage.out ./...
