#!/bin/bash
set -e -o pipefail
export PATH="$PWD/.gobincache:$PATH"
go generate
set -x

scriptsdir=$( dirname -- "$0"; )
cd $scriptsdir/../../
if ! command -v hadolint &> /dev/null; then
    echo "hadolint is not installed or not in PATH, please run 'task scripts:install:hadolint' and try again"
else
    hadolint docker/Dockerfile
    set +x # disable debug output
    export DOPPLER_TOKEN=$(doppler configs tokens create your-token-name-here -p hqservice -c dev --max-age 1m --plain)
    set -x
    go test -race -covermode atomic -coverprofile=coverage.out ./...
    go tool cover -html=coverage.out -o coverage.html
fi
