#!/bin/bash
set -e -o pipefail
export PATH="$PWD/.gobincache:$PATH"
go generate
set -x

scriptsdir=$( dirname -- "$0"; )
cd $scriptsdir/../../

hadolint Dockerfile

# TODO: Set up linting
golangci-lint run

gotestsum -- -race -tags=integration "$@" ./...
