// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Default: ""},
		{Name: "data", Type: field.TypeString, Default: ""},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// ConnectionsColumns holds the columns for the "connections" table.
	ConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Default: ""},
		{Name: "data", Type: field.TypeString, Default: ""},
	}
	// ConnectionsTable holds the schema information for the "connections" table.
	ConnectionsTable = &schema.Table{
		Name:       "connections",
		Columns:    ConnectionsColumns,
		PrimaryKey: []*schema.Column{ConnectionsColumns[0]},
	}
	// IncomesColumns holds the columns for the "incomes" table.
	IncomesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Default: ""},
		{Name: "data", Type: field.TypeString, Default: ""},
	}
	// IncomesTable holds the schema information for the "incomes" table.
	IncomesTable = &schema.Table{
		Name:       "incomes",
		Columns:    IncomesColumns,
		PrimaryKey: []*schema.Column{IncomesColumns[0]},
	}
	// InstitutionsColumns holds the columns for the "institutions" table.
	InstitutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Default: ""},
		{Name: "data", Type: field.TypeString, Default: ""},
	}
	// InstitutionsTable holds the schema information for the "institutions" table.
	InstitutionsTable = &schema.Table{
		Name:       "institutions",
		Columns:    InstitutionsColumns,
		PrimaryKey: []*schema.Column{InstitutionsColumns[0]},
	}
	// ManualItemsColumns holds the columns for the "manual_items" table.
	ManualItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Default: "manual"},
		{Name: "item_table_id", Type: field.TypeString, Default: "asset"},
		{Name: "type", Type: field.TypeString, Default: "cash"},
		{Name: "category", Type: field.TypeString, Default: "asset"},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "value", Type: field.TypeFloat64, Default: 1.401298464324817e-45},
	}
	// ManualItemsTable holds the schema information for the "manual_items" table.
	ManualItemsTable = &schema.Table{
		Name:       "manual_items",
		Columns:    ManualItemsColumns,
		PrimaryKey: []*schema.Column{ManualItemsColumns[0]},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "list_id", Type: field.TypeInt, Default: 0},
		{Name: "text", Type: field.TypeString, Default: ""},
		{Name: "completed", Type: field.TypeBool, Default: false},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Default: ""},
		{Name: "data", Type: field.TypeString, Default: ""},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		ConnectionsTable,
		IncomesTable,
		InstitutionsTable,
		ManualItemsTable,
		TodosTable,
		TransactionsTable,
	}
)

func init() {
}
