FROM alpine:3.17

ARG AUTH_DOMAIN
ARG HQ_AUTH_ADDR_PORT
ARG HQ_NETWORTH_ADDR_PORT

WORKDIR /app

COPY /bin .

EXPOSE ${HQ_AUTH_ADDR_PORT}
EXPOSE ${HQ_NETWORTH_ADDR_PORT}

ENTRYPOINT [ "./hq" ]

CMD [ "serve", "--wa.id", "${AUTH_DOMAIN}", "--wa.origins", "https://${AUTH_DOMAIN}" ]

