// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthAccountParams creates a new GetAuthAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthAccountParams() *GetAuthAccountParams {
	return &GetAuthAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthAccountParamsWithTimeout creates a new GetAuthAccountParams object
// with the ability to set a timeout on a request.
func NewGetAuthAccountParamsWithTimeout(timeout time.Duration) *GetAuthAccountParams {
	return &GetAuthAccountParams{
		timeout: timeout,
	}
}

// NewGetAuthAccountParamsWithContext creates a new GetAuthAccountParams object
// with the ability to set a context for a request.
func NewGetAuthAccountParamsWithContext(ctx context.Context) *GetAuthAccountParams {
	return &GetAuthAccountParams{
		Context: ctx,
	}
}

// NewGetAuthAccountParamsWithHTTPClient creates a new GetAuthAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthAccountParamsWithHTTPClient(client *http.Client) *GetAuthAccountParams {
	return &GetAuthAccountParams{
		HTTPClient: client,
	}
}

/*
GetAuthAccountParams contains all the parameters to send to the API endpoint

	for the get auth account operation.

	Typically these are written to a http.Request.
*/
type GetAuthAccountParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthAccountParams) WithDefaults() *GetAuthAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth account params
func (o *GetAuthAccountParams) WithTimeout(timeout time.Duration) *GetAuthAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth account params
func (o *GetAuthAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth account params
func (o *GetAuthAccountParams) WithContext(ctx context.Context) *GetAuthAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth account params
func (o *GetAuthAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth account params
func (o *GetAuthAccountParams) WithHTTPClient(client *http.Client) *GetAuthAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth account params
func (o *GetAuthAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
