version: "3.9"
services:
  passkey_auth_svc:
    image: ${IMAGE_TAG}
    container_name: passkey-auth-svc
    ports:
      - "${HQ_AUTH_ADDR_PORT:-0}:17000"
    environment:
      DOPPLER_TOKEN: "${DOPPLER_TOKEN}"

    healthcheck:
      test: ["CMD", "nc", "-z", "${HQ_X_POSTGRES_HOST}", "${HQ_X_POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

networks:
  passkey_auth_svc:
    driver: bridge
