version: "3.5"
services:
  cabackend:
    image: ${HQ_SVC_IMAGE_TAG}
    container_name: hq-svc
    ports:
      - "${HQ_AUTH_ADDR_PORT:-0}:17000"
      - "${HQ_NETWORTH_ADDR_PORT}:17002"
    environment:
      # TODO: Need a curl to get all the environments
      HQ_ANDROID_ASSET_LINKS: "${HQ_ANDROID_ASSET_LINKS}"
      HQ_AUTH_ADDR_HOST: "${HQ_AUTH_ADDR_HOST}"
      HQ_AUTH_ADDR_HOST_INT: "${HQ_AUTH_ADDR_HOST_INT}"
      HQ_AUTH_ADDR_PORT: "${HQ_AUTH_ADDR_PORT}"
      HQ_AUTH_ENABLE_TOKEN_HEADER: "${HQ_AUTH_ENABLE_TOKEN_HEADER}"
      HQ_AUTH_RP_ID: "${HQ_AUTH_RP_ID}"
      HQ_AUTH_RP_ORIGINS: "${HQ_AUTH_RP_ORIGINS}"
      HQ_FINVERSE_APP_ID: "${HQ_FINVERSE_APP_ID}"
      HQ_FINVERSE_CLIENT_ID: "${HQ_FINVERSE_CLIENT_ID}"
      HQ_FINVERSE_REDIRECT_URI: "${HQ_FINVERSE_REDIRECT_URI}"
      HQ_FINVERSE_SECRET: "${HQ_FINVERSE_SECRET}"
      HQ_IOS_SITE_ASSOCIATION: "${HQ_IOS_SITE_ASSOCIATION}"
      HQ_JWK_SECRETS: "${HQ_JWK_SECRETS}"
      HQ_JWT_AUDIENCE: "${HQ_JWT_AUDIENCE}"
      HQ_JWT_ISSUER: "${HQ_JWT_ISSUER}"
      HQ_JWT_LIFESPAN: "${HQ_JWT_LIFESPAN}"
      HQ_MAIL_FROM_ADDRESS: "${HQ_MAIL_FROM_ADDRESS}"
      HQ_MAIL_FROM_NAME: "${HQ_MAIL_FROM_NAME}"
      HQ_NETWORTH_ADDR_HOST: "${HQ_NETWORTH_ADDR_HOST}"
      HQ_NETWORTH_ADDR_HOST_INT: "${HQ_NETWORTH_ADDR_HOST_INT}"
      HQ_NETWORTH_ADDR_PORT: "${HQ_NETWORTH_ADDR_PORT}"
      HQ_ONESIGNAL_APP_ID: "${HQ_ONESIGNAL_APP_ID}"
      HQ_ONESIGNAL_APP_KEY: "${HQ_ONESIGNAL_APP_KEY}"
      HQ_PASSCODE_TTL: "${HQ_PASSCODE_TTL}"
      HQ_PLAID_CLIENT_ID: "${HQ_PLAID_CLIENT_ID}"
      HQ_PLAID_COUNTRY_CODES: "${HQ_PLAID_COUNTRY_CODES}"
      HQ_PLAID_ENV: "${HQ_PLAID_ENV}"
      HQ_PLAID_PRODUCTS: "${HQ_PLAID_PRODUCTS}"
      HQ_PLAID_REDIRECT_URI: "${HQ_PLAID_REDIRECT_URI}"
      HQ_PLAID_SECRET: "${HQ_PLAID_SECRET}"
      HQ_POSTGRES_HOST: "${HQ_POSTGRES_HOST}"
      HQ_POSTGRES_LOGIN: "${HQ_POSTGRES_LOGIN}"
      HQ_POSTGRES_NAME: "${HQ_POSTGRES_NAME}"
      HQ_POSTGRES_PASS: "${HQ_POSTGRES_PASS}"
      HQ_POSTGRES_PORT: "${HQ_POSTGRES_PORT}"
      HQ_REQUIRE_EMAIL_VERIFICATION: "${HQ_REQUIRE_EMAIL_VERIFICATION}"
      HQ_SALTEDGE_APP_ID: "${HQ_SALTEDGE_APP_ID}"
      HQ_SALTEDGE_PK: "${HQ_SALTEDGE_PK}"
      HQ_SALTEDGE_SECRET: "${HQ_SALTEDGE_SECRET}"

    healthcheck:
      test: ["CMD", "nc", "-z", "${HQ_POSTGRES_HOST}", "${HQ_POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - intranet

networks:
  intranet:

