version: "3.9"

volumes:
  postgres:

services:
  postgres:
    image: "postgres:15.2"
    container_name: "hq_postgres"
    restart: "always"
    shm_size: "256m"
    ports:
      - "${HQ_POSTGRES_ADDR_PORT:-0}:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${HQ_POSTGRES_AUTH_LOGIN}"
      POSTGRES_PASSWORD: "${HQ_POSTGRES_AUTH_PASS}"

    networks:
      - intranet

networks:
  intranet:

