// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hellohq/hqservice/ent/jwk"
	"github.com/hellohq/hqservice/ent/predicate"
)

// JwkDelete is the builder for deleting a Jwk entity.
type JwkDelete struct {
	config
	hooks    []Hook
	mutation *JwkMutation
}

// Where appends a list predicates to the JwkDelete builder.
func (jd *JwkDelete) Where(ps ...predicate.Jwk) *JwkDelete {
	jd.mutation.Where(ps...)
	return jd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jd *JwkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jd.sqlExec, jd.mutation, jd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jd *JwkDelete) ExecX(ctx context.Context) int {
	n, err := jd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jd *JwkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jwk.Table, sqlgraph.NewFieldSpec(jwk.FieldID, field.TypeUint))
	if ps := jd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jd.mutation.done = true
	return affected, err
}

// JwkDeleteOne is the builder for deleting a single Jwk entity.
type JwkDeleteOne struct {
	jd *JwkDelete
}

// Where appends a list predicates to the JwkDelete builder.
func (jdo *JwkDeleteOne) Where(ps ...predicate.Jwk) *JwkDeleteOne {
	jdo.jd.mutation.Where(ps...)
	return jdo
}

// Exec executes the deletion query.
func (jdo *JwkDeleteOne) Exec(ctx context.Context) error {
	n, err := jdo.jd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jwk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jdo *JwkDeleteOne) ExecX(ctx context.Context) {
	if err := jdo.Exec(ctx); err != nil {
		panic(err)
	}
}
