// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gofrs/uuid"
	"github.com/hellohq/hqservice/ent/webauthnsessiondataallowedcredential"
	"github.com/hellohq/hqservice/ent/webauthnsessiondatum"
)

// WebauthnSessionDatumCreate is the builder for creating a WebauthnSessionDatum entity.
type WebauthnSessionDatumCreate struct {
	config
	mutation *WebauthnSessionDatumMutation
	hooks    []Hook
}

// SetChallenge sets the "challenge" field.
func (wsdc *WebauthnSessionDatumCreate) SetChallenge(s string) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetChallenge(s)
	return wsdc
}

// SetUserID sets the "user_id" field.
func (wsdc *WebauthnSessionDatumCreate) SetUserID(u uuid.UUID) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetUserID(u)
	return wsdc
}

// SetUserVerification sets the "user_verification" field.
func (wsdc *WebauthnSessionDatumCreate) SetUserVerification(s string) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetUserVerification(s)
	return wsdc
}

// SetOperation sets the "operation" field.
func (wsdc *WebauthnSessionDatumCreate) SetOperation(s string) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetOperation(s)
	return wsdc
}

// SetCreatedAt sets the "created_at" field.
func (wsdc *WebauthnSessionDatumCreate) SetCreatedAt(t time.Time) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetCreatedAt(t)
	return wsdc
}

// SetUpdatedAt sets the "updated_at" field.
func (wsdc *WebauthnSessionDatumCreate) SetUpdatedAt(t time.Time) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetUpdatedAt(t)
	return wsdc
}

// SetID sets the "id" field.
func (wsdc *WebauthnSessionDatumCreate) SetID(u uuid.UUID) *WebauthnSessionDatumCreate {
	wsdc.mutation.SetID(u)
	return wsdc
}

// AddWebauthnSessionDataAllowedCredentialIDs adds the "webauthn_session_data_allowed_credentials" edge to the WebauthnSessionDataAllowedCredential entity by IDs.
func (wsdc *WebauthnSessionDatumCreate) AddWebauthnSessionDataAllowedCredentialIDs(ids ...uuid.UUID) *WebauthnSessionDatumCreate {
	wsdc.mutation.AddWebauthnSessionDataAllowedCredentialIDs(ids...)
	return wsdc
}

// AddWebauthnSessionDataAllowedCredentials adds the "webauthn_session_data_allowed_credentials" edges to the WebauthnSessionDataAllowedCredential entity.
func (wsdc *WebauthnSessionDatumCreate) AddWebauthnSessionDataAllowedCredentials(w ...*WebauthnSessionDataAllowedCredential) *WebauthnSessionDatumCreate {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsdc.AddWebauthnSessionDataAllowedCredentialIDs(ids...)
}

// Mutation returns the WebauthnSessionDatumMutation object of the builder.
func (wsdc *WebauthnSessionDatumCreate) Mutation() *WebauthnSessionDatumMutation {
	return wsdc.mutation
}

// Save creates the WebauthnSessionDatum in the database.
func (wsdc *WebauthnSessionDatumCreate) Save(ctx context.Context) (*WebauthnSessionDatum, error) {
	return withHooks[*WebauthnSessionDatum, WebauthnSessionDatumMutation](ctx, wsdc.sqlSave, wsdc.mutation, wsdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wsdc *WebauthnSessionDatumCreate) SaveX(ctx context.Context) *WebauthnSessionDatum {
	v, err := wsdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wsdc *WebauthnSessionDatumCreate) Exec(ctx context.Context) error {
	_, err := wsdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsdc *WebauthnSessionDatumCreate) ExecX(ctx context.Context) {
	if err := wsdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wsdc *WebauthnSessionDatumCreate) check() error {
	if _, ok := wsdc.mutation.Challenge(); !ok {
		return &ValidationError{Name: "challenge", err: errors.New(`ent: missing required field "WebauthnSessionDatum.challenge"`)}
	}
	if _, ok := wsdc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WebauthnSessionDatum.user_id"`)}
	}
	if _, ok := wsdc.mutation.UserVerification(); !ok {
		return &ValidationError{Name: "user_verification", err: errors.New(`ent: missing required field "WebauthnSessionDatum.user_verification"`)}
	}
	if _, ok := wsdc.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "WebauthnSessionDatum.operation"`)}
	}
	if _, ok := wsdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebauthnSessionDatum.created_at"`)}
	}
	if _, ok := wsdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WebauthnSessionDatum.updated_at"`)}
	}
	return nil
}

func (wsdc *WebauthnSessionDatumCreate) sqlSave(ctx context.Context) (*WebauthnSessionDatum, error) {
	if err := wsdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wsdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wsdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wsdc.mutation.id = &_node.ID
	wsdc.mutation.done = true
	return _node, nil
}

func (wsdc *WebauthnSessionDatumCreate) createSpec() (*WebauthnSessionDatum, *sqlgraph.CreateSpec) {
	var (
		_node = &WebauthnSessionDatum{config: wsdc.config}
		_spec = sqlgraph.NewCreateSpec(webauthnsessiondatum.Table, sqlgraph.NewFieldSpec(webauthnsessiondatum.FieldID, field.TypeUUID))
	)
	if id, ok := wsdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wsdc.mutation.Challenge(); ok {
		_spec.SetField(webauthnsessiondatum.FieldChallenge, field.TypeString, value)
		_node.Challenge = value
	}
	if value, ok := wsdc.mutation.UserID(); ok {
		_spec.SetField(webauthnsessiondatum.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := wsdc.mutation.UserVerification(); ok {
		_spec.SetField(webauthnsessiondatum.FieldUserVerification, field.TypeString, value)
		_node.UserVerification = value
	}
	if value, ok := wsdc.mutation.Operation(); ok {
		_spec.SetField(webauthnsessiondatum.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := wsdc.mutation.CreatedAt(); ok {
		_spec.SetField(webauthnsessiondatum.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wsdc.mutation.UpdatedAt(); ok {
		_spec.SetField(webauthnsessiondatum.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := wsdc.mutation.WebauthnSessionDataAllowedCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   webauthnsessiondatum.WebauthnSessionDataAllowedCredentialsTable,
			Columns: []string{webauthnsessiondatum.WebauthnSessionDataAllowedCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: webauthnsessiondataallowedcredential.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WebauthnSessionDatumCreateBulk is the builder for creating many WebauthnSessionDatum entities in bulk.
type WebauthnSessionDatumCreateBulk struct {
	config
	builders []*WebauthnSessionDatumCreate
}

// Save creates the WebauthnSessionDatum entities in the database.
func (wsdcb *WebauthnSessionDatumCreateBulk) Save(ctx context.Context) ([]*WebauthnSessionDatum, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wsdcb.builders))
	nodes := make([]*WebauthnSessionDatum, len(wsdcb.builders))
	mutators := make([]Mutator, len(wsdcb.builders))
	for i := range wsdcb.builders {
		func(i int, root context.Context) {
			builder := wsdcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebauthnSessionDatumMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wsdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wsdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wsdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wsdcb *WebauthnSessionDatumCreateBulk) SaveX(ctx context.Context) []*WebauthnSessionDatum {
	v, err := wsdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wsdcb *WebauthnSessionDatumCreateBulk) Exec(ctx context.Context) error {
	_, err := wsdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsdcb *WebauthnSessionDatumCreateBulk) ExecX(ctx context.Context) {
	if err := wsdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
