// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdditionalProperties AdditionalProperties
//
// swagger:model AdditionalProperties
type AdditionalProperties struct {

	//
	Empty Mapstringinterface `json:",omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *AdditionalProperties) UnmarshalJSON(data []byte) error {
	var props struct {

		//
		Empty Mapstringinterface `json:",omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Empty = props.Empty
	return nil
}

// Validate validates this additional properties
func (m *AdditionalProperties) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this additional properties based on context it is used
func (m *AdditionalProperties) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdditionalProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdditionalProperties) UnmarshalBinary(b []byte) error {
	var res AdditionalProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
