// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NumbersInternational NumbersInternational
//
// swagger:model NumbersInternational
type NumbersInternational struct {

	//
	Empty AdditionalProperties `json:",omitempty"`

	// account id
	// Required: true
	AccountID *string `json:"account_id"`

	// bic
	// Required: true
	Bic *string `json:"bic"`

	// iban
	// Required: true
	Iban *string `json:"iban"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *NumbersInternational) UnmarshalJSON(data []byte) error {
	var props struct {

		//
		Empty AdditionalProperties `json:",omitempty"`

		// account id
		// Required: true
		AccountID *string `json:"account_id"`

		// bic
		// Required: true
		Bic *string `json:"bic"`

		// iban
		// Required: true
		Iban *string `json:"iban"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Empty = props.Empty
	m.AccountID = props.AccountID
	m.Bic = props.Bic
	m.Iban = props.Iban
	return nil
}

// Validate validates this numbers international
func (m *NumbersInternational) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIban(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NumbersInternational) validateAccountID(formats strfmt.Registry) error {

	if err := validate.Required("account_id", "body", m.AccountID); err != nil {
		return err
	}

	return nil
}

func (m *NumbersInternational) validateBic(formats strfmt.Registry) error {

	if err := validate.Required("bic", "body", m.Bic); err != nil {
		return err
	}

	return nil
}

func (m *NumbersInternational) validateIban(formats strfmt.Registry) error {

	if err := validate.Required("iban", "body", m.Iban); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this numbers international based on the context it is used
func (m *NumbersInternational) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEmpty(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NumbersInternational) contextValidateEmpty(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Empty.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NumbersInternational) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NumbersInternational) UnmarshalBinary(b []byte) error {
	var res NumbersInternational
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
