// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PersonalFinanceCategory PersonalFinanceCategory
//
// swagger:model PersonalFinanceCategory
type PersonalFinanceCategory struct {

	//
	Empty AdditionalProperties `json:",omitempty"`

	// detailed
	// Required: true
	Detailed *string `json:"detailed"`

	// primary
	// Required: true
	Primary *string `json:"primary"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *PersonalFinanceCategory) UnmarshalJSON(data []byte) error {
	var props struct {

		//
		Empty AdditionalProperties `json:",omitempty"`

		// detailed
		// Required: true
		Detailed *string `json:"detailed"`

		// primary
		// Required: true
		Primary *string `json:"primary"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Empty = props.Empty
	m.Detailed = props.Detailed
	m.Primary = props.Primary
	return nil
}

// Validate validates this personal finance category
func (m *PersonalFinanceCategory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetailed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrimary(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonalFinanceCategory) validateDetailed(formats strfmt.Registry) error {

	if err := validate.Required("detailed", "body", m.Detailed); err != nil {
		return err
	}

	return nil
}

func (m *PersonalFinanceCategory) validatePrimary(formats strfmt.Registry) error {

	if err := validate.Required("primary", "body", m.Primary); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this personal finance category based on the context it is used
func (m *PersonalFinanceCategory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEmpty(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PersonalFinanceCategory) contextValidateEmpty(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Empty.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PersonalFinanceCategory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonalFinanceCategory) UnmarshalBinary(b []byte) error {
	var res PersonalFinanceCategory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
