// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Connection is the predicate function for connection builders.
type Connection func(*sql.Selector)

// Income is the predicate function for income builders.
type Income func(*sql.Selector)

// Institution is the predicate function for institution builders.
type Institution func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
