// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gofrs/uuid"
	"github.com/hellohq/hqservice/internal/db/sqlite/ent/income"
	"github.com/hellohq/hqservice/internal/db/sqlite/ent/institution"
)

// IncomeCreate is the builder for creating a Income entity.
type IncomeCreate struct {
	config
	mutation *IncomeMutation
	hooks    []Hook
}

// SetInstitutionID sets the "institution_id" field.
func (ic *IncomeCreate) SetInstitutionID(u uuid.UUID) *IncomeCreate {
	ic.mutation.SetInstitutionID(u)
	return ic
}

// SetNillableInstitutionID sets the "institution_id" field if the given value is not nil.
func (ic *IncomeCreate) SetNillableInstitutionID(u *uuid.UUID) *IncomeCreate {
	if u != nil {
		ic.SetInstitutionID(*u)
	}
	return ic
}

// SetData sets the "data" field.
func (ic *IncomeCreate) SetData(s string) *IncomeCreate {
	ic.mutation.SetData(s)
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *IncomeCreate) SetCreatedAt(t time.Time) *IncomeCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *IncomeCreate) SetNillableCreatedAt(t *time.Time) *IncomeCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *IncomeCreate) SetUpdatedAt(t time.Time) *IncomeCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *IncomeCreate) SetNillableUpdatedAt(t *time.Time) *IncomeCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *IncomeCreate) SetID(u uuid.UUID) *IncomeCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ic *IncomeCreate) SetNillableID(u *uuid.UUID) *IncomeCreate {
	if u != nil {
		ic.SetID(*u)
	}
	return ic
}

// SetInstitution sets the "institution" edge to the Institution entity.
func (ic *IncomeCreate) SetInstitution(i *Institution) *IncomeCreate {
	return ic.SetInstitutionID(i.ID)
}

// Mutation returns the IncomeMutation object of the builder.
func (ic *IncomeCreate) Mutation() *IncomeMutation {
	return ic.mutation
}

// Save creates the Income in the database.
func (ic *IncomeCreate) Save(ctx context.Context) (*Income, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *IncomeCreate) SaveX(ctx context.Context) *Income {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *IncomeCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *IncomeCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *IncomeCreate) defaults() {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := income.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := income.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
	if _, ok := ic.mutation.ID(); !ok {
		v := income.DefaultID()
		ic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *IncomeCreate) check() error {
	if _, ok := ic.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "Income.data"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Income.created_at"`)}
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Income.updated_at"`)}
	}
	return nil
}

func (ic *IncomeCreate) sqlSave(ctx context.Context) (*Income, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *IncomeCreate) createSpec() (*Income, *sqlgraph.CreateSpec) {
	var (
		_node = &Income{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(income.Table, sqlgraph.NewFieldSpec(income.FieldID, field.TypeUUID))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ic.mutation.Data(); ok {
		_spec.SetField(income.FieldData, field.TypeString, value)
		_node.Data = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(income.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(income.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ic.mutation.InstitutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   income.InstitutionTable,
			Columns: []string{income.InstitutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(institution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InstitutionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IncomeCreateBulk is the builder for creating many Income entities in bulk.
type IncomeCreateBulk struct {
	config
	builders []*IncomeCreate
}

// Save creates the Income entities in the database.
func (icb *IncomeCreateBulk) Save(ctx context.Context) ([]*Income, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Income, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncomeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *IncomeCreateBulk) SaveX(ctx context.Context) []*Income {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *IncomeCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *IncomeCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
