// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuthAccountHandlerFunc turns a function with the right signature into a get auth account handler
type GetAuthAccountHandlerFunc func(GetAuthAccountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthAccountHandlerFunc) Handle(params GetAuthAccountParams) middleware.Responder {
	return fn(params)
}

// GetAuthAccountHandler interface for that can handle valid get auth account params
type GetAuthAccountHandler interface {
	Handle(GetAuthAccountParams) middleware.Responder
}

// NewGetAuthAccount creates a new http.Handler for the get auth account operation
func NewGetAuthAccount(ctx *middleware.Context, handler GetAuthAccountHandler) *GetAuthAccount {
	return &GetAuthAccount{Context: ctx, Handler: handler}
}

/*
	GetAuthAccount swagger:route GET /auth getAuthAccount

GetAuthAccount get auth account API
*/
type GetAuthAccount struct {
	Context *middleware.Context
	Handler GetAuthAccountHandler
}

func (o *GetAuthAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthAccountParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
