// Code generated by ent, DO NOT EDIT.

package webauthnsessiondata

const (
	// Label holds the string label denoting the webauthnsessiondata type in the database.
	Label = "webauthn_session_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChallenge holds the string denoting the challenge field in the database.
	FieldChallenge = "challenge"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserVerification holds the string denoting the user_verification field in the database.
	FieldUserVerification = "user_verification"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeWebauthnSessionDataAllowedCredentials holds the string denoting the webauthn_session_data_allowed_credentials edge name in mutations.
	EdgeWebauthnSessionDataAllowedCredentials = "webauthn_session_data_allowed_credentials"
	// Table holds the table name of the webauthnsessiondata in the database.
	Table = "webauthn_session_data"
	// WebauthnSessionDataAllowedCredentialsTable is the table that holds the webauthn_session_data_allowed_credentials relation/edge.
	WebauthnSessionDataAllowedCredentialsTable = "webauthn_session_data_allowed_credentials"
	// WebauthnSessionDataAllowedCredentialsInverseTable is the table name for the WebauthnSessionDataAllowedCredential entity.
	// It exists in this package in order to avoid circular dependency with the "webauthnsessiondataallowedcredential" package.
	WebauthnSessionDataAllowedCredentialsInverseTable = "webauthn_session_data_allowed_credentials"
	// WebauthnSessionDataAllowedCredentialsColumn is the table column denoting the webauthn_session_data_allowed_credentials relation/edge.
	WebauthnSessionDataAllowedCredentialsColumn = "webauthn_session_data_id"
)

// Columns holds all SQL columns for webauthnsessiondata fields.
var Columns = []string{
	FieldID,
	FieldChallenge,
	FieldUserID,
	FieldUserVerification,
	FieldOperation,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
