// Code generated by go-swagger; DO NOT EDIT.

package web_authn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hellohq/hqservice/api/openapi/model"
)

// NewWebauthnLoginFinalParams creates a new WebauthnLoginFinalParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWebauthnLoginFinalParams() *WebauthnLoginFinalParams {
	return &WebauthnLoginFinalParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWebauthnLoginFinalParamsWithTimeout creates a new WebauthnLoginFinalParams object
// with the ability to set a timeout on a request.
func NewWebauthnLoginFinalParamsWithTimeout(timeout time.Duration) *WebauthnLoginFinalParams {
	return &WebauthnLoginFinalParams{
		timeout: timeout,
	}
}

// NewWebauthnLoginFinalParamsWithContext creates a new WebauthnLoginFinalParams object
// with the ability to set a context for a request.
func NewWebauthnLoginFinalParamsWithContext(ctx context.Context) *WebauthnLoginFinalParams {
	return &WebauthnLoginFinalParams{
		Context: ctx,
	}
}

// NewWebauthnLoginFinalParamsWithHTTPClient creates a new WebauthnLoginFinalParams object
// with the ability to set a custom HTTPClient for a request.
func NewWebauthnLoginFinalParamsWithHTTPClient(client *http.Client) *WebauthnLoginFinalParams {
	return &WebauthnLoginFinalParams{
		HTTPClient: client,
	}
}

/*
WebauthnLoginFinalParams contains all the parameters to send to the API endpoint

	for the webauthn login final operation.

	Typically these are written to a http.Request.
*/
type WebauthnLoginFinalParams struct {

	/* User.

	   Fields need to update a area
	*/
	User *model.PublicKeyCredentialAssertionResponse

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the webauthn login final params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebauthnLoginFinalParams) WithDefaults() *WebauthnLoginFinalParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the webauthn login final params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebauthnLoginFinalParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the webauthn login final params
func (o *WebauthnLoginFinalParams) WithTimeout(timeout time.Duration) *WebauthnLoginFinalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the webauthn login final params
func (o *WebauthnLoginFinalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the webauthn login final params
func (o *WebauthnLoginFinalParams) WithContext(ctx context.Context) *WebauthnLoginFinalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the webauthn login final params
func (o *WebauthnLoginFinalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the webauthn login final params
func (o *WebauthnLoginFinalParams) WithHTTPClient(client *http.Client) *WebauthnLoginFinalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the webauthn login final params
func (o *WebauthnLoginFinalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the webauthn login final params
func (o *WebauthnLoginFinalParams) WithUser(user *model.PublicKeyCredentialAssertionResponse) *WebauthnLoginFinalParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the webauthn login final params
func (o *WebauthnLoginFinalParams) SetUser(user *model.PublicKeyCredentialAssertionResponse) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *WebauthnLoginFinalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
