name: PostgreSQL

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HQ_POSTGRES_HOST }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          username: trannguyen
          key: ${{ secrets.STAGING_KEY }}
          script: |
            cd $HOME 
            rm -f .env || true
            echo HQ_POSTGRES_PORT=${{ secrets.HQ_POSTGRES_PORT }} >> .env
            echo HQ_POSTGRES_LOGIN=${{ secrets.HQ_POSTGRES_LOGIN }} >> .env
            echo HQ_POSTGRES_PASS=${{ secrets.HQ_POSTGRES_PASS }} >> .env
            docker compose stop postgres || true
            docker compose rm -f postgres || true
            docker compose up -d postgres

      
      

          