name: PostgreSQL

on:
  workflow_dispatch:

env:
  PROJECT_ID: hellohq
  REGION: asia-southeast1-a

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo Hello World

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
          service_account: 'hq-gh-sa@hellohq.iam.gserviceaccount.com'
  
      - name: SSH to VM
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'example-instance'
          zone: 'us-central1-a'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            cd $HOME && \
            export HQ_POSTGRES_AUTH_LOGIN='${{ secrets.HQ_POSTGRES_AUTH_LOGIN }}' && \
            export HQ_POSTGRES_AUTH_PASS='${{ secrets.HQ_POSTGRES_AUTH_PASS }}' && \
            export HQ_POSTGRES_ADDR_PORT='${{ secrets.HQ_POSTGRES_ADDR_PORT }}' && \
            docker compose up -d --remove-orphan
      

          